### PR TITLE
build: upgrade to Go `1.23.0`

### LINKED ISSUE #1492: Upgrade Go version to `1.23`
### What is the version of your ORAS CLI

1.2.0

### What would you like to be added?

Upgrade to `Go 1.23`.

### Why is this needed for ORAS?

[Go 1.23](https://go.dev/doc/go1.23) has been released on 2024-08-13. It is time to upgrade the go version to the latest.

### Are you willing to submit PRs to contribute to this feature?

- [X] Yes, I am willing to implement it.

### PR DESCRIPTION
**Pull request by Wwwsylvia**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1492 

**Please check the following list**:
- [ ]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
Hold this for oras-go?

**Comment by shizhMSFT** [comment]
> Hold this for oras-go?

Not necessary but good to do so.

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by Wwwsylvia** [comment]
`oras-go` is now at Go `1.22`.

**Pull request merged**
