### PR TITLE
feat: Add `oras download` command (WIP)

### PR DESCRIPTION
**Pull request by TerryHowe**
This is pretty rough still, but wanted to get it out for conversation.

Sample Usage:
```
oras download     --ca-file "${REGISTRY_CAFILE}" ${REGISTRY}/curated-packages/prometheus/prometheus@sha256:c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b  ${REGISTRY}/curated-packages/harbor/harbor-registry@sha256:7a4957ddd9228b312125ceb186af9d7e00fe1b8257191fd69cf4df355d1b4cd4
```

Sample output:
```
out/curated-packages/prometheus
out/curated-packages/prometheus/prometheus
out/curated-packages/prometheus/prometheus/sha256:c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b
out/curated-packages/prometheus/prometheus/sha256:c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b/ingest
out/curated-packages/prometheus/prometheus/sha256:c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b/oci-layout
out/curated-packages/prometheus/prometheus/sha256:c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b/blobs
out/curated-packages/prometheus/prometheus/sha256:c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b/blobs/sha256
out/curated-packages/prometheus/prometheus/sha256:c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b/blobs/sha256/9bfcd754305e2db4e9a78e80364d1b2834574c4c2563737f69a26b68dd47e64a
out/curated-packages/prometheus/prometheus/sha256:c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b/blobs/sha256/c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b
out/curated-packages/prometheus/prometheus/sha256:c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b/blobs/sha256/7a378ca94c3456ca82d63bd9c0db672219e968048bd70cdf1c665a05439323e5
out/curated-packages/prometheus/prometheus/sha256:c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b/blobs/sha256/4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
out/curated-packages/prometheus/prometheus/sha256:c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b/blobs/sha256/c9a5b97c2853cff850c4909607f94acb9be4ce12ba0ed7791faf5c6b2ffaddbb
out/curated-packages/prometheus/prometheus/sha256:c551125a624189cece9135981621f3f3144564ddabe14b523507bf74c2281d9b/index.json
```

Partial: https://github.com/oras-project/oras/issues/730

Signed-off-by: Terry Howe <tlhowe@amazon.com>

### CODE REVIEW

**Comment by shizhMSFT** [comment]
It seems that `oras download` functions similar to `oras copy --to-oci-layout` in `oras v1.0.0-rc.1`. Would you like to start a discussion before implementation?

**Comment by sajayantony** [comment]
It’s might be worth considering so many options. Looks like we have pull copy and this would introduce yet another way to obtain content. 

Why not enhance the existing command set to support multiple images?

**Comment by TerryHowe** [comment]
> Why not enhance the existing command set to support multiple images?

I did consider that, but the only sensible command would be `cp` and it has a lot of options already. It would take a lot more options to support this. I've put this up as simple as possible, but I think there are several useful options that could be added to it.

The `cp` command is like the Linux `cp` command and this is more like the `tar` command. I considered making the output of this initially be a tgz, but it was easier to get started with this.

**Comment by sajayantony** [comment]
@TerryHowe are you open to align with how cp on linux supports multiple sources. If there is a strong sentiment to add download as another command then I don't have any concerns, but personally I've begun to prefer cp to move content between different targets.

**Pull request closed without merging**
