### PR TITLE
perf: save auth requests for push and attach

### LINKED ISSUE #1084: Consider optimizing the number of auth requests
### What is the version of your ORAS CLI

1.1.0-rc.2

### What would you like to be added?

I was pushing an empty artifact using the below command and noticed that it took 9 requests to complete.
```sh
oras push $myreg/$myrepo:$mytag --debug
```

The requests were:

request `#0`: HEAD manifest digest - 401
request `#1`: POST token (scope: pull) - 200
request `#2`: HEAD manifest digest - 404
request `#3`: HEAD config ({}) - 404
<ins>request `#4`: POST config ({}) - 401</ins>
<ins>request `#5`: POST token (scope: pull, push) - 200</ins>
request `#6`: POST config ({}) - 202
request `#7`: PUT config ({}) - 201
request `#8`: PUT manifest tag - 201

It looks like the auth-related requests `#4` and `#5` (the one with underlines) can be saved on ORAS side.

### Why is this needed for ORAS?

This can further improve the performance of ORAS.

### Are you willing to submit PRs to contribute to this feature?

- [x] Yes, I am willing to implement it.

### PR DESCRIPTION
**Pull request by Wwwsylvia**
**What this PR does / why we need it**:
Add `pull, push` scope hints before calling `Copy` for `oras push` and `oras attach`. 
This can potentially save 2 requests for each command.

### oras push
```sh
oras push $myreg/$myrepo:$mytag --debug
```
#### Before
request `#0`: HEAD manifest digest - 401
request `#1`: POST token (scope: pull) - 200
request `#2`: HEAD manifest digest - 404
request `#3`: HEAD config ({}) - 404
<ins>request `#4`: POST config ({}) - 401</ins>
<ins>request `#5`: POST token (scope: pull, push) - 200</ins>
request `#6`: POST config ({}) - 202
request `#7`: PUT config ({}) - 201
request `#8`: PUT manifest tag - 201

#### After
request `#0`: HEAD manifest digest - 401
request `#1`: POST token (scope: pull) - 200
request `#2`: HEAD manifest digest - 404
request `#3`: HEAD config ({}) - 404
request `#4`: POST config ({}) - 202
request `#5`: PUT config ({}) - 201
request `#6`: PUT manifest tag - 201

### oras attach
```sh
oras attach myreg/myrepo:mytag --artifact-type application/test foo --debug
```

#### Before

request `#0`: HEAD subject tag - 401  
request `#1`: POST token (scope: pull) - 200  
request `#2`: HEAD subject tag - 200  
request `#3`: HEAD manifest digest - 404  
request `#4`: HEAD config ({}) - 200  
request `#5`: HEAD layer - 404  
<ins>request `#6`: POST layer - 401</ins>
<ins>request `#7`: POST token (scope: pull, push) - 200</ins>
request `#8`: POST layer - 202  
request `#9`: PUT layer - 201  
request `#10`: PUT manifest tag - 201  

#### After

request `#0`: HEAD subject tag - 401  
request `#1`: POST token (scope: pull) - 200  
request `#2`: HEAD subject tag - 200  
request `#3`: HEAD manifest digest - 404  
request `#4`: HEAD config ({}) - 200  
request `#5`: HEAD layer - 404  
request `#6`: POST layer - 202  
request `#7`: PUT layer - 201  
request `#8`: PUT manifest tag - 201  

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1084 

**Please check the following list**:
- [ ]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [x]  Do all new files have an appropriate license header?

### CODE REVIEW

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by qweeah — COMMENTED** [review]
LGTM  but this change also be applied to manifest delete and blob delete

**Comment by TerryHowe** [comment]
> LGTM but this change can also be applied to manifest delete and blob delete

Follow up?

**Comment by Wwwsylvia** [comment]
> > > LGTM but this change can also be applied to manifest delete and blob delete
> > 
> > 
> > Follow up?
> 
> Created #1104. @Wwwsylvia Do we still need to create the issue for copying?

Created #1105

**Pull request merged**
