### PR TITLE
fix: platform config type

### PR DESCRIPTION
**Pull request by TerryHowe**
**What this PR does / why we need it**:

Fix platform config type.

**Which issue(s) this PR fixes**

Fixes https://github.com/oras-project/oras/issues/1517

### CODE REVIEW

**Comment by Wwwsylvia** [comment]
Looks like some E2E tests failed

**Comment by TerryHowe** [comment]
> Looks like some E2E tests failed

Fixed.

**Review by Wwwsylvia — APPROVED** [review]
LGTM, but I am not a maintainer

**Review by qweeah — APPROVED** [review]
LGTM

**Pull request merged**
