### PR TITLE
fix: coverage.txt file generation contained testutils

### PR DESCRIPTION
**Pull request by TerryHowe**
**What this PR does / why we need it**:

coverage.txt contained testutils on the last PR https://github.com/oras-project/oras/pull/1443/files#diff-bd7e25b9d11cd3ad1fe54a05a85404a42102e79be984f3f5ae2377c7e95e2eda

### CODE REVIEW

**Comment by qweeah** [comment]
Checked [uploaded coverage.txt](https://[storage.googleapis.com/codecov/v4/raw/2024-08-09/A303CDB7247354348852E1C9BB266CBE/141c5e107301b3e0c41805b8628a16f4e165bcbf/13cfe138-45ae-4fd7-b686-0e35271c3a8d/1a0d20bc-c3c3-40ef-99d3-3f5b0b2fb594.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=GOOG1EJOGFN2JQ4OCTGA2MU5AEIT7OT5Z7HTFOAN2SPG4NWSN2UJYOY5U6LZQ%2F20240810%2Fus-west2%2Fs3%2Faws4_request&X-Amz-Date=20240810T042150Z&X-Amz-Expires=30&X-Amz-SignedHeaders=host&X-Amz-Signature=4eb5b21e6d90fe27523ea8762a3ddcdefcff5fc129c6e787765a89983c35d077](https://storage.googleapis.com/codecov/v4/raw/2024-08-09/A303CDB7247354348852E1C9BB266CBE/141c5e107301b3e0c41805b8628a16f4e165bcbf/13cfe138-45ae-4fd7-b686-0e35271c3a8d/1a0d20bc-c3c3-40ef-99d3-3f5b0b2fb594.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=GOOG1EJOGFN2JQ4OCTGA2MU5AEIT7OT5Z7HTFOAN2SPG4NWSN2UJYOY5U6LZQ%2F20240810%2Fus-west2%2Fs3%2Faws4_request&X-Amz-Date=20240810T042150Z&X-Amz-Expires=30&X-Amz-SignedHeaders=host&X-Amz-Signature=4eb5b21e6d90fe27523ea8762a3ddcdefcff5fc129c6e787765a89983c35d077)) and looks like e2e is messing the calculation. Should remove `internal/testutils` related coverage in Makefile `teste2e-covdata` target

**Comment by TerryHowe** [comment]
I'm seeing testutils in my coverage.txt on my mac and I don't run the teste2e-covdata target.

**Comment by qweeah** [comment]
Looks like the coverage upload fails. See https://app.codecov.io/github/oras-project/oras/commit/e583297cb9d361c5c9a122ea01e97879c6da14b6

**Comment by qweeah** [comment]
My latest update avoids unwanted packages in generated coverage.txt but still there are codecov errors when consuming it.

**Comment by qweeah** [comment]
@TerryHowe Suggest to close the PR since Codecov returns false positive when any file packge line is removed from the generated report (see [error here](https://app.codecov.io/github/oras-project/oras/commit/aa2de72d81a333aba260350914ff0a9826859abf)). I think it's a bug in Codecov service and we are not able to exclude `internal/testutils` from coverage calculation if we are using Codecov.

**Comment by TerryHowe** [comment]
Sounds good. In theory, we shouldn't need the same mock in multiple packages anyway IMO. I hope testutils can be reduced or eliminated.

**Pull request closed without merging**
