### PR TITLE
build(ci): release artifacts for freebsd

### LINKED ISSUE #1179: FreeBSD builds
### What is the version of your ORAS CLI

_No response_

### What would you like to be added?

We would like to use oras cli to pull artifacts on FreeBSD based servers. Unfortunately the darwin builds aren't compatible.

### Why is this needed for ORAS?

This would expand the potential user base to all popular systems.

### Are you willing to submit PRs to contribute to this feature?

- [ ] Yes, I am willing to implement it.

### PR DESCRIPTION
**Pull request by kranurag7**
Adds support for oras on freebsd os. It adds make target for compiling oras binary on freebsd and updates goreleaser config to release for freebsd as well.

> [!NOTE]
> I've not tested it on a freebsd system. I only tested go compiling the program to an executable.

#### make targets 

```bash
$ make build-freebsd
GOARCH=amd64 CGO_ENABLED=0 GOOS=freebsd go build -v --ldflags="-w -X oras.land/oras/internal/version.GitCommit=9ecf303eeb2620dfe3ddf15721999d1f7e8fd4bf -X oras.land/oras/internal/version.GitTreeState=dirty" \
	-o bin/freebsd/amd64/oras oras.land/oras/cmd/oras
$ file bin/freebsd/amd64/oras
bin/freebsd/amd64/oras: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), statically linked, for FreeBSD 12.3, FreeBSD-style, Go BuildID=nJPfJNS3LfJNcKUnioi_/X0yuGUxMlHdwTByT063Y/VfH381P8Oh6iX6eAu6qc/FP_dvr9XPXmKk77-JLXA, not stripped
```

#### goreleaser snapshot

```bash
$ goreleaser release --snapshot
# truncated 
    • creating                                       archive=dist/oras_1.1.0-SNAPSHOT-9ecf303_freebsd_amd64.tar.gz
$ file dist/oras_freebsd_amd64_v1/oras
dist/oras_freebsd_amd64_v1/oras: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), statically linked, for FreeBSD 12.3, FreeBSD-style, stripped
$ tar -tf dist/oras_1.1.0-SNAPSHOT-9ecf303_freebsd_amd64.tar.gz
LICENSE
oras
```

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1179 

**Please check the following list**:
- [ ]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [x]  Do all new files have an appropriate license header?

### CODE REVIEW

**Comment by rchincha** [comment]
cc: @dfr

**Comment by dfr** [comment]
> cc: @dfr

I can test this on a FreeBSD system - I'll take a look later today.

**Comment by FeynmanZhou** [comment]
Thank you @rchincha and @dfr !

**Comment by tmaroschik** [comment]
I verified that the build works on our freebsd 13.2 on amd64. Thanks!

**Comment by FeynmanZhou** [comment]
> I verified that the build works on our freebsd 13.2 on amd64. Thanks!

Thanks @tmaroschik for the verification! 

Hi @oras-project/oras-cli maintainers, any luck with reviewing or approving this PR?

**Comment by kranurag7** [comment]
@FeynmanZhou We have one request above about arm64 binaries. 

> It would be nice to have arm64 binaries as well. 

Do you want to proceed with that in this PR?

**Comment by dfr** [comment]
> @FeynmanZhou We have one request above about arm64 binaries.
> 
> > It would be nice to have arm64 binaries as well.
> 
> Do you want to proceed with that in this PR? The original issue was only about amd64 binaries, so I skipped other arch.

I'm happy to move forward as-is and look into adding arm64 as a followup.

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by SamirPS** [comment]
I would try to add other arch, into this PR but else LGTM

**Review by qweeah — APPROVED** [review]
LGTM.

ORAS CLI will be guaranteed to build on FreeBSD(see Tier 2 in https://github.com/oras-project/oras-www/issues/277).

**Pull request merged**
